### ISSUE TITLE
Implement audio preparation

### ISSUE THREAD

**Issue by fedirsmilianets** [fedirsmilianets/yaacrl#4]
Open and prepare audio with ffmpeg directly, instead of pydub, used in [dejavu](https://github.com/worldveil/dejavu)

**Comment by fedirsmilianets** [comment]
I found that libavcodec should be used for it.

**Comment by daniildxb** [comment]
Closed by commit 329cbfc8741e567ed2b447a0b138f66b2d1faffc

**Comment by fedirsmilianets** [comment]
Closed by commit [805af88](https://github.com/ffluffyhedgehog/yaacrl/commit/805af88867c080fa5cf7c6c49c8ce8c41dd20760)

**Comment by fedirsmilianets** [comment]
re-done using dr_wav in [b5d2b2c](https://github.com/ffluffyhedgehog/yaacrl/commit/b5d2b2c4af3d3bbfc4ddff0b5ed833218bb889b8)
